### ISSUE TITLE
Refactor resource selection

### ISSUE THREAD

**Issue by cswaney** [princeton-ddss/blackfish#182]
## Description

Resource selection is cluster-dependent. This feature provides a mechanism for Slurm cluster admins to specify the resources available to Blackfish.

Calculating suggestions for minimal device memory based on model information is complicated because it relies on knowledge of hardware details as well as the actual meaning of constraints. 

In terms of HPC admin, I propose to pull resource specification from a shared file, `slurm.yaml`, located in `<cache_dir>/config`. The file contents would look something like this:

```yaml
# cache_dir/config/slurm.yaml

default:
  nodes:
    default: 1
    max: 1
  ntasks-per-node:
    default: 4
    max: 8
  mem:
    default: 8G
    max: 256G
  gres:
    default: gpu
    values:
      gpu:
        default: a100
        values:
          null:
            default: 1
            max: 4
          a100:
            default: 1
            max: 4
          h100:
            default: 1
            max: 4
  constraints:
    - gpu40
    - gpu80
    - amd&gpu40 # 100%
    - intel&gpu40 # 50%

mig:
  nodes:
    max: 1
  ntasks-per-node:
    max: 1
  mem:
    max: 32G
  gres:
    default: gpu
    values:
      gpu:
        default: null
        null:
          default: 1
          max: 1
  time:
    max: 01:00:00

pli:
  nodes:
    max: 1
  ntasks-per-node:
    max: 8
  mem:
    max: 640G
  gres:
    default: gpu
    values:
      gpu:
        default: null
        null:
          default: 1
          max: 8
```

If this file is missing, then we would use a default configuration. The values in this file determine the available and default options for all supported SLURM `sbatch` arguments. The slurm configs should be handled as Pydantic objects and exposed via a new `api/resources` endpoint that returns the resource config based on a given profile.

On the frontend, we will add new logic to consume the resources endpoint and use it to populate default selector values and validation parameters (e.g.,  `max`, `min`). 

### Backend
1. New `resources.py` with Pydantic models for YAML schema
2. API endpoint `GET /api/resources?profile=<name>`
3. Update `SlurmJobConfig` to support `gres_type` for GPU selection
4. Update SBATCH template for `--gres=gpu:<type>:<count>` format

### Frontend

1. `useResourceConfig` hook for fetching config
2. New components: `PartitionSelect`, `ConstraintSelect`, `GpuTypeSelect`
3. Refactor `ServiceModalForm` to use dynamic validation limits from config
4. Add `partition`, `constraint`, GPU type, and `account` fields

### Testing

- Unit tests for Pydantic models and config loading
- API tests for the new endpoint
- Component tests for new selectors

## Out of Scope

In terms of providing suggestions to users, the main issue is how much GPU memory is required. In general, a precise calculation requires knowledge of model architecture in order to calculate the size of the key-value cache:

```javascript
/**
 * Calculates the virtual memory used by KV cache.
 * @param {number} batch_size - Size of the batch.
 * @param {number} seq_len - Sequence length.
 * @param {number} num_layers - Number of layers in the model.
 * @param {number} num_heads - Number of attention heads.
 * @param {number} dim_head - Dimension of each attention head.
 * @param {number} precision - Precision in bytes.
 * @returns {number} Virtual memory used by KV cache in bytes.
 */
function kv_cache_vmem() {
    batch_size * seq_len * (2 * num_layers * num_heads * dim_head * precision)
}
```

The required model architecture is **not** provided by the Hugging Face API, so we would need to extract it when a model is added. For now, I would suggest using a baseline of `1G` for a `batch_size=1` and `seq_len=4096`.

The other component of required memory is based on API-provided values that we can easily record when the model is added:

```javascript
/**
 * Precision mapping in bytes for different data types.
 * @const {Object.<string, number>}
 */
const PRECISION = {
    'F16': 2,
    'B32': 4,
    'B64': 8,
    'I8': 1,
    'I16': 2,
    'I32': 4,
    'I64': 8,
}

/**
 * Calculates total memory required for model parameters.
 * @param {Array|Object} params - Model parameters with precision and size.
 * @returns {number} Total memory usage in bytes.
 */
function params_vmem(params) {
    let vmem = 0;
    for (const [precision, size] in params) {
        vmem += size * PRECISION[precision];
    }
    return vmem
}
```
